name: Integration

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm test

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: create .env
        run: |
          echo "NEXT_PUBLIC_API_URL = https://strapi.rezaa.me \
            API_KEY= ${{secrets.API_KEY}} \
            WAKA_KEY= ${{secrets.WAKA_KEY}} \
            WAKA_COUNTRY_CODE = ID \
            NEXT_PUBLIC_WAKA_COUNTRY = Indonesia} \
            GITHUB_USERNAME = rezaageng \
            GITHUB_KEY= ${{secrets.GH_KEY}} \
            LEETCODE_USERNAME = rezaageng" > .env
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm build
